### ISSUE TITLE
LRU and LFU cache implementation

### ISSUE THREAD

**Issue by dzakaammar** [bxcodec/gotcha#19]
What a nice package you've been worked on! I learn how the algorithm behind the cache works through reading your implementation.

Btw, I have concerning something about the LRU and LFU cache implementation. I can't see the differences between both implementations in `lfu.go` and `lru.go` file. Is it better if we just merge them into one and let the `Options` decide its implementation by init the selected repository?

**Comment by bxcodec** [comment]
Sure, it will look more tidy and clear without redundant code. 
Do you want to do it?  Or me?

**Comment by bxcodec** [comment]
nevermind, I'll do this.
